import 'package:json_annotation/json_annotation.dart';
// The import 'package:json_annotation/json_annotation.dart'; statement imports
// the necessary annotations for JSON serialization.
part "../login_request_body.g.dart";
// The part "login_request_body.g.dart"; statement specifies the part file
// that will be generated by the build runner for JSON serialization.

@JsonSerializable()
// The @JsonSerializable() annotation marks the LoginRequestBody class
//for JSON serialization.
class LoginRequestBody {
  // The class has two final fields email and password of type String, which are
  // required parameters in the constructor.
  final String email;
  final String password;
  LoginRequestBody({
    required this.email,
    required this.password,
  });

  Map<String, dynamic> toJson() => _$LoginRequestBodyToJson(
        this,
        // this refers to the current instance of the class. In the context of
        // the code snippet provided, this is used within the toJson() method of
        // the LoginRequestBody class to refer to the current instance of the
        // LoginRequestBody object being converted to a JSON format.
      );
  // The toJson() method converts the LoginRequestBody object to a Map<String,
  // dynamic> using the generated method _$LoginRequestBodyToJson(this).
  // This method is generated by the build runner based on
  // the @JsonSerializable() annotation.

  // Example usage :
  // LoginRequestBody requestBody = LoginRequestBody(email: 'test@example.com', password: 'password123');
  // Map<String, dynamic> json = requestBody.toJson();
  // print(json);
}
// This is a simple Dart class named LoginRequestBody with two final fields:
// email and password, both of type String. The constructor requires these
// fields to be passed in when creating an instance of the class.
