name: docspot
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.5.0-180.3.beta <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  # A powerful HTTP client for Dart, which supports interceptors, global configuration, FormData, request cancellation, file downloading, and timeout.
  easy_localization: ^3.0.7
  # A localization library for Flutter that simplifies the process of translating your app into different languages.
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  # A predictable state management library that helps implement the BLoC (Business Logic Component) design pattern.
  flutter_native_splash: ^2.4.0
  # A package to automatically generate native splash screens for both Android and iOS.
  freezed: ^2.5.3
  # A code generator for unions/pattern-matching/copy in Dart, which helps in creating immutable classes.
  freezed_annotation: ^2.4.1
  # Annotations for the freezed package, used to define data classes and unions.
  get_it: ^7.7.0
  # A simple service locator for Dart and Flutter projects, which is used for dependency injection.
  intl: ^0.19.0
  # A package for internationalization and localization, which includes utilities for formatting dates, numbers, and messages.
  json_annotation: ^4.9.0
  # Annotations for the json_serializable package, used to define how JSON serialization should be handled.
  json_serializable: ^6.8.0
  # A code generator for JSON serialization in Dart, which generates code for converting JSON to Dart objects and vice versa.
  pretty_dio_logger: ^1.3.1
  # A Dio interceptor that logs network calls in a pretty, easy-to-read format.
  retrofit: ^4.1.0
  # A type-safe HTTP client generator for Dart and Flutter, inspired by Retrofit from the Android world.
  retrofit_generator: ^8.1.0
  # A code generator for the retrofit package, which generates the necessary code for making HTTP requests.


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
