import 'package:json_annotation/json_annotation.dart';

part 'specializations_response_model.g.dart';

@JsonSerializable()
// package will generate the necessary code to handle JSON serialization.

class SpecializationsResponseModel {
  SpecializationsResponseModel({
    this.specializationDataList,
  });

  factory SpecializationsResponseModel.fromJson(Map<String, dynamic> json) =>
      _$SpecializationsResponseModelFromJson(json);
  // This is a factory constructor that creates an instance of
  // SpecializationsResponseModel from a JSON object.
  // The method _$SpecializationsResponseModelFromJson(json) is
  // generated by the json_serializable package.

  @JsonKey(name: 'data')
  // This annotation maps the specializationDataList field to the data key in
  // the JSON.
  List<SpecializationsData?>? specializationDataList;
  // The List<SpecializationsData?>? specializationDataList;
  // fieldrepresents a list of SpecializationsData objects, each
  // corresponding to an item in the data array in the JSON response.
}

@JsonSerializable()
class SpecializationsData {
  // This class represents the individual specialization data items.
  SpecializationsData({
    this.id,
    this.name,
    this.doctorsList,
  });

  factory SpecializationsData.fromJson(Map<String, dynamic> json) =>
      _$SpecializationsDataFromJson(json);
  // this factory constructor creates an instance of
  // SpecializationsData from a JSON object.

  @JsonKey(name: 'doctors')
  // This field maps to the doctors key in the JSON, containing
  // a list of DoctorsModel objects.
  List<DoctorsModel?>? doctorsList;

  int? id;
  String? name;
}

@JsonSerializable()
class DoctorsModel {
  //  This class models the individual doctor data.

  DoctorsModel({
    this.id,
    this.name,
    this.email,
    this.phone,
    this.photo,
    this.gender,
    this.price,
    required this.degree,
  });

  factory DoctorsModel.fromJson(Map<String, dynamic> json) =>
      _$DoctorsModelFromJson(json);
  // This factory constructor creates an instance of DoctorsModel
  // from a JSON object.

  String degree;
  String? email;
  String? gender;
  int? id;
  String? name;
  String? phone;
  String? photo;
  @JsonKey(name: 'appoint_price')
  // The price field is mapped to the appoint_price key in the JSON.
  int? price;
}
