// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV5sxpTMU7tWvxT6lAJ2dCQe6MBSOCGpI',
    appId: '1:485574926364:web:7d6511076e357d83f6bfd9',
    messagingSenderId: '485574926364',
    projectId: 'doc-spot-a9142',
    authDomain: 'doc-spot-a9142.firebaseapp.com',
    storageBucket: 'doc-spot-a9142.appspot.com',
    measurementId: 'G-9V3Z4MEXN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2OIClQUAIKw-WJP2z_5LHM3z1dyDoE7g',
    appId: '1:485574926364:android:7bba1c78bbd04ad4f6bfd9',
    messagingSenderId: '485574926364',
    projectId: 'doc-spot-a9142',
    storageBucket: 'doc-spot-a9142.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4QlPeQfQLyIqRDP3shja1ixCYsr28ZLQ',
    appId: '1:485574926364:ios:3e5f96c0a566ae19f6bfd9',
    messagingSenderId: '485574926364',
    projectId: 'doc-spot-a9142',
    storageBucket: 'doc-spot-a9142.appspot.com',
    iosBundleId: 'com.example.docspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4QlPeQfQLyIqRDP3shja1ixCYsr28ZLQ',
    appId: '1:485574926364:ios:3e5f96c0a566ae19f6bfd9',
    messagingSenderId: '485574926364',
    projectId: 'doc-spot-a9142',
    storageBucket: 'doc-spot-a9142.appspot.com',
    iosBundleId: 'com.example.docspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV5sxpTMU7tWvxT6lAJ2dCQe6MBSOCGpI',
    appId: '1:485574926364:web:37510a7ff8c6e341f6bfd9',
    messagingSenderId: '485574926364',
    projectId: 'doc-spot-a9142',
    authDomain: 'doc-spot-a9142.firebaseapp.com',
    storageBucket: 'doc-spot-a9142.appspot.com',
    measurementId: 'G-PSJ0D4FY08',
  );
}
