import 'package:json_annotation/json_annotation.dart';
part 'signup_request_body.g.dart';

@JsonSerializable()
// @JsonSerializable(): Annotation to indicate that this class should have
// JSON serialization code generated for it.

class SignupRequestBody {
  final String name;
  // final String name;: A required field for the user's name.
  final String email;
  // final String email;: A required field for the user's email.
  final String phone;
  // final String phone;: A required field for the user's phone number.
  final String password;
  // final String password;: A required field for the user's password.
  @JsonKey(name: 'password_confirmation')
  final String passwordConfirmation;
  // final String passwordConfirmation;: A required field for password
  // confirmation, with a custom key name password_confirmation in the JSON.
  final int gender;
  // A required field for the user's gender.

  SignupRequestBody({
    required this.name,
    required this.email,
    required this.phone,
    required this.password,
    required this.passwordConfirmation,
    required this.gender,
  });

  Map<String, dynamic> toJson() => _$SignupRequestBodyToJson(this);
  // A method to convert an instance of SignupRequestBody to a JSON map.
  // The _$SignupRequestBodyToJson function is generated by the
  // json_serializable package.
}
