import 'package:json_annotation/json_annotation.dart';
part 'signup_response.g.dart';

@JsonSerializable()
// @JsonSerializable(): Annotation to indicate that this class should have
//JSON serialization code generated for it.
class SignupResponse {
  String? message;
  // String? message;: A nullable string field to hold a message from
  // the response.
  @JsonKey(name: 'data')
  UserData? userData;
  // @JsonKey(name: 'data') UserData? userData;: A nullable UserData field,
  // with a custom key name data in the JSON.
  bool? status;
  // bool? status;: A nullable boolean field to indicate the status of the
  // response.
  int? code;
  // int? code;: A nullable integer field to hold a response code.

  SignupResponse({this.message, this.userData, this.status, this.code});

  factory SignupResponse.fromJson(Map<String, dynamic> json) =>
      _$SignupResponseFromJson(json);
  // A factory constructor to create an instance of SignupResponse from
  // a JSON map. The _$SignupResponseFromJson function is generated by the
  // json_serializable package.
}

@JsonSerializable()
class UserData {
  String? token;
  // String? token;: A nullable string field to hold a token.
  @JsonKey(name: 'username')
  String? userName;
  // @JsonKey(name: 'username') String? userName;: A nullable string field for
  // the username, with a custom key name username in the JSON.

  UserData({this.token, this.userName});

  factory UserData.fromJson(Map<String, dynamic> json) =>
      _$UserDataFromJson(json);
  //  A factory constructor to create an instance of UserData from a JSON
  // map. The _$UserDataFromJson function is generated by the
  // json_serializable package.
}
